name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: sudo apt-get install avr-gcc libc-avr binutils-avr
    - name: make
      run: make
    - name: make check
      run: make check
